language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - g++-4.8
    - cmake
    - cmake-data
    - python

matrix:
  include:
    - compiler: gcc

install:
    - pip install --user gitpython
    - pip install --user six

script:
    - python run.py -f

notifications:
  email: false
